name: e_commerse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl_phone_number_input: ^0.7.4
  flutter_otp_text_field: ^1.1.3+2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_image_slideshow: ^0.1.6
  email_validator: ^2.1.17
  achievement_view: ^1.0.1
  dio: ^5.4.2+1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# flutter_native_splash-development.yaml
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  android_gravity: fill

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"
    android_gravity: fill

  web: false
